site_name: Nimble Exporter
site_description: Nimble Streamer's API Guide
repo_url: https://github.com/shima-original/nimble_exporter
use_directory_urls: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition:
  - pymdownx.arithmatex:
      generic: true
  - footnotes:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.mark
  - attr_list
  - pymdownx.arithmatex:
site_url: http://127.0.0.1:8000/
nav:
- Table of Contents:
  - What is Nimble Exporter: index.md 
  - Structs:
    - About: Structs/index.md
    - ServerStatus: Structs/ServerStatus.md
    - SrtReceivers: Structs/SrtReceivers.md
    - SrtSenders: Structs/SrtSenders.md
  - Functions:
    - About: Functions/index.md
    - processRequest: Functions/processRequest.md
  
plugins:
    - search
    - include_dir_to_nav:
        file_pattern: '^(?!index\.(md|html)).*\.md$'
theme:
   name: material
   custom_dir: overrides
   features:
     - toc.integrate
     - search.suggest
     - search.highlight
     - content.tabs.link
     - content.code.annotation
     - content.code.copy
   language: en
   palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
        primary: teal
        accent: purple
      - scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
        primary: teal
        accent: lime

extra:
  generator: false
  base_url: http://127.0.0.1:8000

 



